In [8]:
import numpy as np
import pandas as pd

path = r'..\data\distance.csv'
path

'..\\data\\distance.csv'

In [10]:
data = pd.read_csv(path)
data.head()

num           A0           A1           A2           A3   x    y   z  label
0    0  1016.931217  4782.857143  4552.962963  6298.994709  50   50  88      1
1    1  1338.424658  4920.136986  4109.178082  5943.561644  50  100  88      1
2    2  1783.790850  5033.464052  3605.882353  5619.150327  50  150  88      1
3    3  2253.617021  5218.563830  3085.159574  5322.819149  50  200  88      1
4    4  2727.142857  5370.285714  2600.142857  5033.238095  50  250  88      1

In [11]:
data.describe()

num           A0           A1           A2           A3  \
count  648.000000   648.000000   648.000000   648.000000   648.000000   
mean   323.500000  3822.361982  3831.485685  3805.228393  3794.452339   
std    187.205769  1303.943989  1302.120626  1304.315800  1301.366632   
min      0.000000   637.966102   578.874172   589.223301   568.910891   
25%    161.750000  2890.911486  2868.041425  2880.476026  2879.709870   
50%    323.500000  3948.425892  3974.006815  4003.183876  3961.648936   
75%    485.250000  4732.334546  4783.172269  4742.382789  4712.299331   
max    647.000000  6707.976654  6657.439614  6607.129630  6464.470588   

                x           y           z       label  
count  648.000000  648.000000  648.000000  648.000000  
mean   250.000000  250.000000  147.000000    0.500000  
std    129.199174  129.199174   42.187042    0.500386  
min     50.000000   50.000000   88.000000    0.000000  
25%    150.000000  150.000000  119.500000    0.000000  
50%    250.000000  250.000000  150.000000    0.500000  
75%    350.000000  350.000000  177.500000    1.000000  
max    450.000000  450.000000  200.000000    1.000000

In [15]:
arr = np.arange(20).reshape(2, 10)
isinstance(arr, np.ndarray)

True

In [17]:
arr[:, 1:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [29]:
train = data.iloc[:, 1:-1]
train = train.to_numpy(np.float64)
train

array([[1016.931217, 4782.857143, 4552.962963, ...,   50.      ,
          50.      ,   88.      ],
       [1338.424658, 4920.136986, 4109.178082, ...,   50.      ,
         100.      ,   88.      ],
       [1783.79085 , 5033.464052, 3605.882353, ...,   50.      ,
         150.      ,   88.      ],
       ...,
       [5822.246377, 3505.942029, 4698.405797, ...,  450.      ,
         350.      ,  200.      ],
       [6195.945946, 3998.198198, 4578.018018, ...,  450.      ,
         400.      ,  200.      ],
       [6556.183206, 4520.305344, 4496.259542, ...,  450.      ,
         450.      ,  200.      ]])

In [34]:
from sklearn.preprocessing import MinMaxScaler

def normalization(X:np.ndarray):
    if not isinstance(X, np.ndarray):
         X = np.array(X)
    minmax = MinMaxScaler()  # 对象实例化
    X = minmax.fit_transform(X)
    return X

train = normalization(train)
train

array([[0.06243237, 0.69160775, 0.65865759, ..., 0.        , 0.        ,
        0.        ],
       [0.1153966 , 0.714192  , 0.58491352, ..., 0.        , 0.125     ,
        0.        ],
       [0.18876816, 0.73283572, 0.50128049, ..., 0.        , 0.25      ,
        0.        ],
       ...,
       [0.85408093, 0.48153925, 0.68282593, ..., 1.        , 0.75      ,
        1.        ],
       [0.91564583, 0.56252155, 0.662821  , ..., 1.        , 0.875     ,
        1.        ],
       [0.97499289, 0.6484147 , 0.64923514, ..., 1.        , 1.        ,
        1.        ]])

In [67]:
data = np.arange(30).reshape(10, 3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [78]:
from sklearn.model_selection import train_test_split

x, y = data[:, 0:-1], data[:, -1]
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=22) # 训练集：测试集 = 7:3
x_train, x_test, y_train, y_test
x_train.size, len(x_train), x_train.shape, len(x)
y_train, y_train[0]

(array([20, 11, 23,  2, 26, 14, 17]), 20)

In [64]:
648*0.75

486.0

In [110]:
from sklearn.model_selection import train_test_split

data = pd.read_csv(path)
data = data.to_numpy(dtype=np.float64)
x, y = data[:, 1:-1], data[:, -1]
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, random_state=22) # 训练集：测试集 = 7:3
x_train.shape, x_test.shape, y_train.shape, y_test.shape

y_test

array([0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1.,
       1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1.,
       0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1.,
       1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1.])

In [99]:
len(data)*0.2

129.6